version: "3"
services:
  app_react:
    build: ./front-end
    container_name: app_react
    volumes:
      - build_react:/var/www/html

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - build_react:/var/www/html
    depends_on:
      - app_react

  db:
    image: postgres
    container_name: db
    restart: always
    ports:
      - 2345:5432
    env_file:
      - ./back-end/.env.production
    healthcheck:
      test: pg_isready -U postgres
    volumes:
      - postgres:/var/lib/postgresql/data

  node_app:
    container_name: node_app
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    env_file:
      - ./back-end/.env.production
    depends_on:
      db:
        condition: service_healthy

volumes:
  build_react:
  postgres:
