name: TestsAndDeploy
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  tests:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Make tests envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_POSTGRES_USER: "postgres"
          envkey_POSTGRES_PASSWORD: "postgres"
          envkey_POSTGRES_DB: "students_test"
          envkey_DATABASE_URL: "postgresql://postgres:postgres@db_test:5432/students_test?schema=public"
          directory: back-end
          file_name: .env.test

      - name: Run tests
        run: docker-compose -f back-end/docker-compose.test.yml up --exit-code-from node_app_tests

  deploy:
    environment: production
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Echo user
        run: echo $USER

      - name: Make tests envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_POSTGRES_USER: "postgres"
          envkey_POSTGRES_PASSWORD: "postgres"
          envkey_POSTGRES_DB: "students"
          envkey_DATABASE_URL: "postgresql://postgres:postgres@db:5432/students?schema=public"
          file_name: .env.production

      - name: Compose up App
        run: docker-compose -f docker-compose.prod.yml up
